import { jsPDF } from 'jspdf'
import 'jspdf-autotable'
import * as XLSX from 'xlsx'

// Types for reporting
export interface ReportData {
  id: string
  title: string
  type: 'executive' | 'operational' | 'audit' | 'performance'
  data: any[]
  metadata: {
    generatedAt: Date
    generatedBy: string
    department: string
    period: string
    filters?: Record<string, any>
  }
}

export interface ExportOptions {
  format: 'pdf' | 'excel' | 'csv' | 'json'
  fileName?: string
  template?: 'standard' | 'executive' | 'detailed'
  includeCharts?: boolean
  includeMetadata?: boolean
}

// PDF Export utility
export class PDFExporter {
  private doc: jsPDF

  constructor() {
    this.doc = new jsPDF()
  }

  generateReport(report: ReportData, options: ExportOptions = { format: 'pdf' }): void {
    this.addHeader(report)
    this.addMetadata(report.metadata)
    this.addExecutiveSummary(report)
    this.addDataTable(report.data)
    this.addFooter()

    const fileName = options.fileName || `${report.title.replace(/\s+/g, '_')}_${Date.now()}.pdf`
    this.doc.save(fileName)
  }

  private addHeader(report: ReportData): void {
    this.doc.setFontSize(20)
    this.doc.setFont('helvetica', 'bold')
    this.doc.text('Track - Railway Management System', 20, 30)
    
    this.doc.setFontSize(16)
    this.doc.text(report.title, 20, 50)
    
    this.doc.setFontSize(10)
    this.doc.setFont('helvetica', 'normal')
    this.doc.text(`Report Type: ${report.type.toUpperCase()}`, 20, 65)
    
    // Add logo if available
    // this.doc.addImage(logoData, 'PNG', 150, 10, 40, 20)
  }

  private addMetadata(metadata: ReportData['metadata']): void {
    const startY = 80
    
    this.doc.setFontSize(12)
    this.doc.setFont('helvetica', 'bold')
    this.doc.text('Report Information', 20, startY)
    
    this.doc.setFontSize(10)
    this.doc.setFont('helvetica', 'normal')
    this.doc.text(`Generated: ${metadata.generatedAt.toLocaleString()}`, 20, startY + 15)
    this.doc.text(`Generated By: ${metadata.generatedBy}`, 20, startY + 25)
    this.doc.text(`Department: ${metadata.department}`, 20, startY + 35)
    this.doc.text(`Period: ${metadata.period}`, 20, startY + 45)
  }

  private addExecutiveSummary(report: ReportData): void {
    const startY = 140
    
    this.doc.setFontSize(12)
    this.doc.setFont('helvetica', 'bold')
    this.doc.text('Executive Summary', 20, startY)
    
    // Calculate key metrics
    const totalRecords = report.data.length
    const summary = this.generateSummaryStats(report.data)
    
    this.doc.setFontSize(10)
    this.doc.setFont('helvetica', 'normal')
    this.doc.text(`Total Records: ${totalRecords}`, 20, startY + 15)
    this.doc.text(`Success Rate: ${summary.successRate}%`, 20, startY + 25)
    this.doc.text(`Processing Time: ${summary.avgProcessingTime}ms`, 20, startY + 35)
  }

  private addDataTable(data: any[]): void {
    if (data.length === 0) return

    const startY = 200
    const columns = Object.keys(data[0])
    const rows = data.map(item => columns.map(col => String(item[col] || '')))

    // Use jspdf-autotable plugin
    ;(this.doc as any).autoTable({
      startY,
      head: [columns],
      body: rows,
      theme: 'grid',
      styles: { fontSize: 8 },
      headStyles: { fillColor: [41, 128, 185] },
      alternateRowStyles: { fillColor: [245, 245, 245] }
    })
  }

  private addFooter(): void {
    const pageCount = this.doc.getNumberOfPages()
    
    for (let i = 1; i <= pageCount; i++) {
      this.doc.setPage(i)
      this.doc.setFontSize(8)
      this.doc.text(
        `Page ${i} of ${pageCount} | Generated by Track Railway Management System`,
        20,
        this.doc.internal.pageSize.height - 10
      )
    }
  }

  private generateSummaryStats(data: any[]): {
    successRate: number
    avgProcessingTime: number
  } {
    const successCount = data.filter(item => item.status === 'success' || item.success).length
    const successRate = data.length > 0 ? Math.round((successCount / data.length) * 100) : 0
    
    const processingTimes = data
      .filter(item => item.processingTime)
      .map(item => item.processingTime)
    
    const avgProcessingTime = processingTimes.length > 0
      ? Math.round(processingTimes.reduce((sum, time) => sum + time, 0) / processingTimes.length)
      : 0
    
    return { successRate, avgProcessingTime }
  }
}

// Excel Export utility
export class ExcelExporter {
  generateReport(report: ReportData, options: ExportOptions = { format: 'excel' }): void {
    const workbook = XLSX.utils.book_new()
    
    // Add main data sheet
    const dataSheet = XLSX.utils.json_to_sheet(report.data)
    XLSX.utils.book_append_sheet(workbook, dataSheet, 'Data')
    
    // Add summary sheet
    const summaryData = this.generateSummarySheet(report)
    const summarySheet = XLSX.utils.json_to_sheet(summaryData)
    XLSX.utils.book_append_sheet(workbook, summarySheet, 'Summary')
    
    // Add metadata sheet
    const metadataSheet = XLSX.utils.json_to_sheet([{
      'Report Title': report.title,
      'Report Type': report.type,
      'Generated At': report.metadata.generatedAt.toISOString(),
      'Generated By': report.metadata.generatedBy,
      'Department': report.metadata.department,
      'Period': report.metadata.period,
      'Total Records': report.data.length
    }])
    XLSX.utils.book_append_sheet(workbook, metadataSheet, 'Metadata')
    
    const fileName = options.fileName || `${report.title.replace(/\s+/g, '_')}_${Date.now()}.xlsx`
    XLSX.writeFile(workbook, fileName)
  }

  private generateSummarySheet(report: ReportData): any[] {
    const summary = []
    
    // Basic statistics
    summary.push({
      Metric: 'Total Records',
      Value: report.data.length
    })
    
    if (report.data.length > 0) {
      const firstItem = report.data[0]
      
      // Count by status if available
      if ('status' in firstItem) {
        const statusCounts = report.data.reduce((acc, item) => {
          acc[item.status] = (acc[item.status] || 0) + 1
          return acc
        }, {} as Record<string, number>)
        
        Object.entries(statusCounts).forEach(([status, count]) => {
          summary.push({
            Metric: `${status.toUpperCase()} Count`,
            Value: count
          })
        })
      }
    }
    
    return summary
  }
}

// CSV Export utility
export class CSVExporter {
  generateReport(report: ReportData, options: ExportOptions = { format: 'csv' }): void {
    const csv = this.arrayToCSV(report.data)
    const fileName = options.fileName || `${report.title.replace(/\s+/g, '_')}_${Date.now()}.csv`
    
    this.downloadCSV(csv, fileName)
  }

  private arrayToCSV(data: any[]): string {
    if (data.length === 0) return ''
    
    const headers = Object.keys(data[0])
    const csvRows = [
      headers.join(','),
      ...data.map(row =>
        headers.map(header => {
          const value = row[header]
          return typeof value === 'string' ? `"${value.replace(/"/g, '""')}"` : value
        }).join(',')
      )
    ]
    
    return csvRows.join('\n')
  }

  private downloadCSV(csv: string, fileName: string): void {
    const blob = new Blob([csv], { type: 'text/csv' })
    const url = window.URL.createObjectURL(blob)
    const link = document.createElement('a')
    
    link.href = url
    link.download = fileName
    link.click()
    
    window.URL.revokeObjectURL(url)
  }
}

// Main Export Manager
export class ExportManager {
  private pdfExporter = new PDFExporter()
  private excelExporter = new ExcelExporter()
  private csvExporter = new CSVExporter()

  async export(report: ReportData, options: ExportOptions): Promise<void> {
    try {
      switch (options.format) {
        case 'pdf':
          this.pdfExporter.generateReport(report, options)
          break
        case 'excel':
          this.excelExporter.generateReport(report, options)
          break
        case 'csv':
          this.csvExporter.generateReport(report, options)
          break
        case 'json':
          this.exportJSON(report, options)
          break
        default:
          throw new Error(`Unsupported export format: ${options.format}`)
      }
    } catch (error) {
      console.error('Export failed:', error)
      throw error
    }
  }

  private exportJSON(report: ReportData, options: ExportOptions): void {
    const jsonData = JSON.stringify(report, null, 2)
    const fileName = options.fileName || `${report.title.replace(/\s+/g, '_')}_${Date.now()}.json`
    
    const blob = new Blob([jsonData], { type: 'application/json' })
    const url = window.URL.createObjectURL(blob)
    const link = document.createElement('a')
    
    link.href = url
    link.download = fileName
    link.click()
    
    window.URL.revokeObjectURL(url)
  }
}

// Report Templates
export const reportTemplates = {
  executive: {
    title: 'Executive Summary Report',
    type: 'executive' as const,
    sections: ['overview', 'kpis', 'trends', 'recommendations']
  },
  operational: {
    title: 'Operational Report',
    type: 'operational' as const,
    sections: ['activities', 'performance', 'issues', 'metrics']
  },
  audit: {
    title: 'Audit Report',
    type: 'audit' as const,
    sections: ['compliance', 'findings', 'risks', 'actions']
  },
  performance: {
    title: 'Performance Report',
    type: 'performance' as const,
    sections: ['metrics', 'benchmarks', 'analysis', 'recommendations']
  }
}

// Scheduled reporting functionality
export class ScheduledReportManager {
  private schedules: Map<string, {
    id: string
    reportType: string
    frequency: 'daily' | 'weekly' | 'monthly'
    recipients: string[]
    lastRun?: Date
    nextRun: Date
  }> = new Map()

  scheduleReport(config: {
    reportType: string
    frequency: 'daily' | 'weekly' | 'monthly'
    recipients: string[]
    startDate?: Date
  }): string {
    const id = crypto.randomUUID()
    const startDate = config.startDate || new Date()
    
    let nextRun: Date
    switch (config.frequency) {
      case 'daily':
        nextRun = new Date(startDate.getTime() + 24 * 60 * 60 * 1000)
        break
      case 'weekly':
        nextRun = new Date(startDate.getTime() + 7 * 24 * 60 * 60 * 1000)
        break
      case 'monthly':
        nextRun = new Date(startDate)
        nextRun.setMonth(nextRun.getMonth() + 1)
        break
    }
    
    this.schedules.set(id, {
      id,
      reportType: config.reportType,
      frequency: config.frequency,
      recipients: config.recipients,
      nextRun
    })
    
    return id
  }

  getSchedules(): Array<{
    id: string
    reportType: string
    frequency: string
    recipients: string[]
    lastRun?: Date
    nextRun: Date
  }> {
    return Array.from(this.schedules.values())
  }

  removeSchedule(id: string): boolean {
    return this.schedules.delete(id)
  }

  // This would be called by a background job
  checkPendingReports(): Array<{
    id: string
    reportType: string
    recipients: string[]
  }> {
    const now = new Date()
    const pending = []
    
    for (const schedule of this.schedules.values()) {
      if (schedule.nextRun <= now) {
        pending.push({
          id: schedule.id,
          reportType: schedule.reportType,
          recipients: schedule.recipients
        })
      }
    }
    
    return pending
  }
}